### ISSUE TITLE
Import error GOMP_4.0

### ISSUE THREAD

**Issue by rduflou** [ghisvail/pyNFFT#55]
I'm rather new to using gitub so I'm not entirely sure this is where to go with my error, but I'm not sure where else I can ask it.

The issue is when I try to import pynfft with:

from pynfft import NFFT

I get the following error:

Traceback (most recent call last):
  File "/home/rutger/Dropbox/Thesis/Shell scripts/save2data3.py", line 10, in <module>
    from pynfft import NFFT
  File "/home/rutger/anaconda2/lib/python2.7/site-packages/pynfft/**init**.py", line 20, in <module>
    from pynfft.nfft import NFFT
ImportError: /home/rutger/anaconda2/lib/libgomp.so.1: version `GOMP_4.0' not found (required by /usr/local/lib/libnfft3_threads.so.1)

I managed to find out GOMP_4.0 is only supported from gcc 4.9 onwards, which is the compiler used for the c-scripts if I'm not mistaking. Updating to a newer version of gcc does not help however.
Compilation of NFFT and pyNFFT is also without problems. It's only when importing that I get an error. This is all for Ubuntu 16.04.

Thanks in advance and my apologies if this is not the place for asking this question.

**Comment by ghisvail** [comment]
> ImportError: /home/rutger/anaconda2/lib/libgomp.so.1: version `GOMP_4.0' not found (required by /usr/local/lib/libnfft3_threads.so.1)

Which toolchain did you use to compile `NFFT`? If you used the default `gcc` of Ubuntu, then you should be using `libgomp.so.1` from the system, **not** from *anaconda*. I suspect the shadowing comes from an override of `LD_LIBRARY_PATH`?

**Comment by rduflou** [comment]
I think it would be the default gcc. I first compiled nfft3.3 before I had anaconda installed. The incompatibility with nfft3.3 later on resulted in some problems and one of the solutions I tried was installing anaconda. Afterwards, I found the problem was the compatibility and switched to nfft3.2. 
I had anaconda installed at this point, but haven't actually used it for anything during compilation and compilation looked rather similar to the first try before anaconda was installed.

I don't know how to force ubuntu to change which libgomp.so.1 to use, but I'll try uninstalling anaconda for now and see if that changes anything.

**Comment by rduflou** [comment]
It worked. I didn't even have to uninstall anaconda but only comment out its PATH variable in the .bashrc file. It then automatically referred to the correct gcc version and corresponding libgomp.so.1. 
Or at least I assume so because importing pynfft and running a few of its methods did not raise any errors, so I think the problem is solved.

Thank you very much.
